SELECT ENAME, DNAME FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND EMP.ENAME='SMITH'

DELETE FROM EMP WHERE ENAME = 'SMITH'

DELETE FROM DEPT WHERE DEPTNO = 20

ROLLBACK;
COMMIT;

SELECT EMPNO FROM EMP   --옵티마이저

SELECT ENAME FROM EMP   --전체를 다 읽었다~


INSERT INTO BANK (NAME, CARDNO, HP)
 VALUES('내복이', 1234, '0103218')

SELECT DEPT.DEPTNO, NAME FROM DEPT, BANK
WHERE DEPT.DEPTNO = BANK.DEPTNO


우리회사에 근무하는 사원중에서 급여가 2500불 이상인 사원의 이름과 급여액을
출력하는 SQL문을 작성하시오.

문제뜻을 분석
집합이름 뭐지? 사원집합 - EMP
어떤 정보를 보여줘야하는거니? 이름과 급여,  ENAME , SAL
결과는 어떤 폼으로 보여주면 될까?
원하는 조건이 있는거니? 

WHERE sal >=2000

SELECT ENAME, SAL
 FROM EMP
 WHERE SAL >=2500



SELECT ENAME,SAL FROM EMP WHERE SAL >=2500 


DROP TABLE BANK

문제2
우리 회사에 근무하는 사원들 중에서 부서번호가 20 혹은 30번 부서에 근무하는 사원들의
사원명, 부서번호, SAL를 출력하는 SQL 문을 작성하시오.

WHERE DEPTNO IN(20,30)

SELECT ENAME, DEPTNO, SAL 
FROM EMP 
WHERE DEPTNO IN(20, 30);


SELECT ENAME, DEPTNO, SAL 
FROM EMP 
WHERE DEPTNO = 20 
OR DEPTNO= 30


우리회사에 근무하는 사원들 중에서 인센티브를 받는 사원들의 이름, 인센티브 금액을 출력하는 SQL문을 작성하시오.


SELECT 1+2, 2+NULL FROM dual

dual : 컬럼하나에 로우하나짜리 가상 테이블


SELECT sysdate FROM dual


SELECT SYSDATE, TO_CHAR(sysdate,'YYYY')
,TO_CHAR(sysdate, 'day')
FROM dual


SELECT ENAME, COMM FROM EMP 
WHERE COMM IS NOT NULL;

SELECT ENAME, COMM FROM EMP
WHERE COMM > 0



SELECT ENAME, COMM FROM EMP  --14건

NULL인 경우는 제외한다.

SELECT ENAME, COMM FROM EMP 
WHERE COMM IS NOT NULL
AND COMM !=0





SELECT 1+2, 3*5, 5/10, sysdate+1 FROM DUAL

SELECT 와 FROM절 사이에 컬럼이 온다
SELECT 와 FROM절 사이에 사칙연산이 가능하다.
SELECT 와 FROM절 사이에 함수를 사용할 수 있다.
SELECT 와 FROM절 사이에 컬럼을 추가하면 테이블의 오른쪽이 늘어나요.
테이블의 아래쪽을 늘일려면 INSERT



SELECT 1,2,3,4,5,6,7,'안녕' FROM dual;



SELECT EMPNO, ENAME, JOB, SAL, COMM,HIREDATE, DEPTNO, MGR FROM EMP







SELECT ENAME, COMM FROM EMP
MINUS
SELECT ENAME, COMM FROM EMP 
WHERE COMM=0
MINUS
SELECT ENAME, COMM FROM EMP
WHERE COMM IS NULL; 

INSERT INTO BANK (NAME) VALUES ('내복이');