SELECT MEM_ID, MEM_PW, MEM_NAME, MEM_ADDR, MEM_ZIPCODE
FROM MEMBER

DELETE FROM MEMBER WHERE MEM_ID='K'

COMMIT;

INSERT INTO MEMBER (MEM_ID, MEM_NAME, MEM_ADDR,MEM_PW,MEM_ZIPCODE)
VALUES ('DD','DD','DD','DD','DD')

DELETE FROM MEMBER WHERE mem_id='DD'

SELECT ZIPCODE,ADDRESS FROM zipcode_t
WHERE dong LIKE '%'||'°¡»êµ¿'||'%'