/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-24 09:24:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String c_name=null;
	Cookie cookies[] = request.getCookies();
		for(int i=0;i<cookies.length;i++){
			out.print("쿠키정보: "+cookies[i].getValue());
			if(cookies[i].getName().equals("c_name")){
				c_name=cookies[i].getValue();
			out.print("c_name"+c_name);
			}
	}
	if(c_name==null){
		response.sendRedirect("a.jsp");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>Add and Remove Layout - jQuery EasyUI Demo</title>\r\n");
      out.write("   <!-- easyui.css는 jeasyui가 제공하는 콤포넌트(예:datagrid, layout 등)에 디자인을 입힐 때 사용됨 -->\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"../themes/default/easyui.css\">\r\n");
      out.write("   <!--  icon.css는 아이콘 이미지 처리하는데 사용됨 -->\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"../themes/icon.css\">\r\n");
      out.write("   <!--  jeasyui 데모페이지에 사용되는 css임 -->\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"../demo/demo.css\">\r\n");
      out.write("   <!-- jeasyui가 jquery 기반이므로 호환성을 검증한 스크립트 코드만 따로 모아둠 -->\r\n");
      out.write("   <script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("   <!-- \r\n");
      out.write("   jeasyui가 jquery 기반이므로 아래 파일을 import하기 전에 반드시 jquery.min.js가\r\n");
      out.write("   import 되어있어야 함. 순서 반드시 지킬 것!   \r\n");
      out.write("    -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write(" \t//입력 다이얼로그 창 열기\r\n");
      out.write(" \t\r\n");
      out.write(" \t/**************************************************************\r\n");
      out.write(" \t*입력화면에서 저장버튼 클릭했을 때 \r\n");
      out.write(" \t* 사용자가 입력한 정보를 서버로 (Tomcat) 전송해야함.\r\n");
      out.write(" \t* get 인터셉트를 한다. 누가 (브라우저)->서버로 요청이 전송되지 않음.\r\n");
      out.write(" \t* 한 번 요청된 페이지는 각 사용자 pc에 그 내용이 다운로드\r\n");
      out.write(" \t* 두 번째 같은 페이지를 요청하면 서버에 전달한 다음 응답을 받아오는 것이 아니라\r\n");
      out.write(" \t* xxx.html?1 주소창에 다른 글자를 한자로 붙이면 새로운 요청으로 인식\r\n");
      out.write(" \t* xxx.html?mem_id=test&mem_pw=123 (보안상 취약함)\r\n");
      out.write(" \t* 브라우저마다(탭마다도 해당)\r\n");
      out.write(" \t* 브라우저가 열릴 때 마다 네이버 서버측에서 너에게 세션아이디\r\n");
      out.write(" \t* 사용자 컴퓨터에 있는 정보가 그대로 다시 출력된다.\r\n");
      out.write(" \t* 클라이언트 측에 다운로드(html, css,js)\r\n");
      out.write(" \t* <form>태그 ->method ->get(default-인터셉트)|post,action->\r\n");
      out.write(" \t*****************************************************************/\r\n");
      out.write("\t\t    function myformatter(date){\r\n");
      out.write("\t\t        var y = date.getFullYear();\r\n");
      out.write("\t\t        var m = date.getMonth()+1;\r\n");
      out.write("\t\t        var d = date.getDate();\r\n");
      out.write("\t\t        return y+'-'+(m<10?('0'+m):m)+'-'+(d<10?('0'+d):d);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    function myparser(s){\r\n");
      out.write("\t\t        if (!s) return new Date();\r\n");
      out.write("\t\t        var ss = (s.split('-'));\r\n");
      out.write("\t\t        var y = parseInt(ss[0],10);\r\n");
      out.write("\t\t        var m = parseInt(ss[1],10);\r\n");
      out.write("\t\t        var d = parseInt(ss[2],10);\r\n");
      out.write("\t\t        if (!isNaN(y) && !isNaN(m) && !isNaN(d)){\r\n");
      out.write("\t\t            return new Date(y,m-1,d);\r\n");
      out.write("\t\t        } else {\r\n");
      out.write("\t\t            return new Date();\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \tfunction add(){\r\n");
      out.write("\t\t \t\t//alert(\"하이\");\r\n");
      out.write("\t\t \t\t$(\"#f_add\").submit();//전송. 어디로 가는거지? ->아까 액션에 있던 이름을 말해주면 돼! 전송방식? get\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \tfunction cancel(){\r\n");
      out.write("\t\t \t\t$('#dlg_add').dialog('close');\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t//입력 다이얼로그창 열기\r\n");
      out.write("\t\t \tfunction addForm(){\r\n");
      out.write("\t\t \t\t$('#dlg_add').dialog('open');\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t//수정 다이얼로그 열기\r\n");
      out.write("\t\t \tfunction updForm(){\r\n");
      out.write("\t\t \t\tvar row = $(\"#dg_member\").datagrid(\"getSelected\");\r\n");
      out.write("\t\t \t\t//datagridid 초기화시 소문자로 작성하였으므로 반드시 소문자로 접근해야함.\r\n");
      out.write("\t\t \t\t//만일 대문자로 작성하면 undefine\r\n");
      out.write("\t\t \t\tvar c_id = row.id;\r\n");
      out.write("\t\t \t\t//alert(c_id;)\r\n");
      out.write("\t\t \t\t//톰캣 서버로 이 아이디와 같은 상세정보를 조회하면 화면에 출력\r\n");
      out.write("\t\t \t\tlocation.href=\"./memberUpdateForm.jsp?id=\"+c_id;\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t    //이름으로 검색하기\r\n");
      out.write("\t\t    function nameSearch(){\r\n");
      out.write("\t\t    \talert(\"nameSearch호출 성공\");\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    //로그인 요청시 호출\r\n");
      out.write("\t\t    function loginAction(){\r\n");
      out.write("\t\t    \t//front-end언어는 오라클 서버와 연동할 수 없다. 상수처리한다.\r\n");
      out.write("\t\t    \tvar db_name = \"내복\";\r\n");
      out.write("\t\t\t\tvar db_id = \"test\";\r\n");
      out.write("\t\t\t\tvar db_pw = \"123\";\r\n");
      out.write("\t\t\t\tvar u_id = $(\"#r_id\").val();\r\n");
      out.write("\t\t\t\tvar u_pw = $(\"#r_pw\").val();\r\n");
      out.write("\t\t\t\tif(db_id==u_id){//아이디가 존재하니?\r\n");
      out.write("\t\t\t\t\tif(db_pw==u_pw){//비번까지 같은거야\"\r\n");
      out.write("\t\t\t\t\t\t//로그인 폼 숨기고 대신 로그인 성공화면 show\r\n");
      out.write("\t\t\t\t\t\t$(\"#r_login\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#r_logout\").show();\r\n");
      out.write("\t\t\t\t\t\t//span태그에 메시지를 추가  - 김유신님 환영합니다.\r\n");
      out.write("\t\t\t\t\t\t$(\"#s_msg\").html(\"<b>\"+db_name+\"</b>님 환영합니다.\")\r\n");
      out.write("\t\t\t\t\t\t}else{//비번이 틀린 거 같아\r\n");
      out.write("\t\t\t\t\t\t\talert(\"비번이 틀렸습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#r_pw\").textbox('setValue','');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else{//아이디가 존재하지 않아\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    //로그아웃 요청시 구현\r\n");
      out.write("\t\t   \tfunction logoutAction(){\r\n");
      out.write("\t\t   \t \t$(\"#r_logout\").hide();\r\n");
      out.write("\t\t   \t \t$(\"#r_login\").show();\r\n");
      out.write("\t\t   \t \t$(\"#r_id\").textbox('setValue','');//속성,벨류\r\n");
      out.write("\t\t   \t \t$(\"#r_pw\").textbox('setValue','');//속성,벨류\r\n");
      out.write("\t\t   \t \t}\r\n");
      out.write("    \t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--  \r\n");
      out.write("\t/*****************************************************************\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t밑에 위에 갖다 쓴거는 함수를 써서 그 때만 바꿔준거~\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t날짜 포맷 형식을 디폴트에서 사용자 정의로 변경하므로\r\n");
      out.write(" \t\tbody태그 안에 해당 콤포넌트가 정의되기 전에 처리함.\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tdatabox에 대한 날짜 포맷 재정의함\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t\r\n");
      out.write(" \t******************************************************************/ -->\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#r_login {<!--\r\n");
      out.write("\t\t\tborder: 1px solid green; -->\r\n");
      out.write("\t\t\twidth: 180px;\r\n");
      out.write("\t\t\theight: 110px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$.fn.datebox.defaults.formatter = function(date){\r\n");
      out.write("\t\t\tvar y = date.getFullYear();\r\n");
      out.write("\t\t\tvar m = date.getMonth()+1;\r\n");
      out.write("\t\t\tvar d = date.getDate();\r\n");
      out.write("\t\t\treturn y+'-'+(m<10 ? \"0\"+m:m)+'-'+(d<10 ? \"0\"+d:d);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.fn.datebox.defaults.parser = function(s){\r\n");
      out.write("\t\t\tvar t = Date.parse(s);\r\n");
      out.write("\t\t\tif (!isNaN(t)){\r\n");
      out.write("\t\t\t\treturn new Date(t);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn new Date();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            /*회원 관리에 필요한 데이터 그리드 추가 - 설정*/\r\n");
      out.write("            $(\"#dg_member\").datagrid({\r\n");
      out.write("         \t   singleSelect:'true'\r\n");
      out.write("                ,toolbar:\"#rbar_member\"\r\n");
      out.write("         \t   ,columns:[[\r\n");
      out.write("         \t\t    {field:'id' ,title:'아이디', width:100} /* 아이디 */\r\n");
      out.write("         \t\t   ,{field:'name',title:'이름', width:120} /* 이름    */\r\n");
      out.write("         \t\t   ,{field:'address',title:'주소', width:300} /* 주소   */\r\n");
      out.write("         \t\t   ,{field:'hp',title:'hp', width:140} /* hp  */   \t   \r\n");
      out.write("         \t   ]]           \t   \r\n");
      out.write("            });///////////////////end of dg_member\r\n");
      out.write("            /*사원 관리에 필요한 데이터 그리드 추가 - 설정*/\r\n");
      out.write("        $(\"#dg_emp\").datagrid({\r\n");
      out.write("            url:'jsonEmp.json'\r\n");
      out.write("           ,columns:[[\r\n");
      out.write("         \t\t{field:'empno',title:'사원번호', width:100} \r\n");
      out.write("         \t\t,{field:'ename',title:'사원명', width:120, edtior:'text'} \r\n");
      out.write("         \t\t,{field:'hiredate',title:'입사일자', width:300} \r\n");
      out.write("         \t\t,{field:'deptno',title:'부서번호', width:140,\r\n");
      out.write("         \t\t\tformatter:function(value,row){\r\n");
      out.write("         \t\t\t\treturn row.deptno||value;\r\n");
      out.write("         \t\t}}\r\n");
      out.write("         \t\t  \r\n");
      out.write("         \t\t\r\n");
      out.write("         \t]]\r\n");
      out.write("               ,editor:{\r\n");
      out.write("            \t   type:'combobox'\r\n");
      out.write("            \t  ,option:{\r\n");
      out.write("            \t\t  valueField:'deptno'\r\n");
      out.write("            \t\t ,textField:'dname'\r\n");
      out.write("            \t  }\r\n");
      out.write("               }\r\n");
      out.write("         \t   ,url:'./jsonEmp.json'\r\n");
      out.write("         \t   ,singleSelect:'true'\r\n");
      out.write("               ,toolbar:\"#rbar_emp\"\r\n");
      out.write("              \r\n");
      out.write("            });///////////////////end of dg_emp\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t//세개 페이지 (회원관리,대여관리,상품관리) 숨김 처리하기 시작\r\n");
      out.write("        \t\t\t$(\"#r_member\").hide();\r\n");
      out.write("            \t\t$(\"#r_rental\").hide();\r\n");
      out.write("            \t\t$(\"#r_prod\").hide();\r\n");
      out.write("            \t\t$(\"#r_emp\").hide();\r\n");
      out.write("            \t\t  //로그인 성공했을 때 화면을 숨기자\r\n");
      out.write("                    $(\"#r_logout\").hide();\r\n");
      out.write("           //easyui에서 제공하는 tree객체에 onClick 이벤트 처리하기 시작\r\n");
      out.write("            $('#te_menu').tree({ //따로 함수 선언하지 않고 즉시 처리\r\n");
      out.write("            \t//파라미터로 넘어오는 node는 사용자가 선택한 엘리먼트 정보 가짐\r\n");
      out.write("\t\t\tonClick: function(node){ //트리메뉴 선택헀을 때 이벤트 처리\r\n");
      out.write("\t\t\t//alert(node.text);  // alert node text property when clicked\r\n");
      out.write("\t\t\t//node.text하면 선택한 노드문자열 가져옴.\r\n");
      out.write("            if(\"회원관리\"==node.text){//너 회원관리 누른거야?\r\n");
      out.write("            \t\t//show메소드 호출하면 화면에 출력되고\r\n");
      out.write("            \t\t//hide메소드 호출하면 화면에 숨김 처리됨.\r\n");
      out.write("            \t\t$(\"#r_member\").show();\r\n");
      out.write("            \t\t$(\"#r_rental\").hide();\r\n");
      out.write("            \t\t$(\"#r_prod\").hide();\r\n");
      out.write("            \t\t$(\"#r_emp\").hide();\r\n");
      out.write("            }\r\n");
      out.write("            else if(\"대여관리\"==node.text){\r\n");
      out.write("         \t\t\t$(\"#r_member\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_rental\").show();\r\n");
      out.write("        \t\t\t$(\"#r_prod\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_emp\").hide();\r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("            else if(\"상품관리\"==node.text){\r\n");
      out.write("         \t\t\t$(\"#r_member\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_rental\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_prod\").show();\r\n");
      out.write("        \t\t\t$(\"#r_emp\").hide();\r\n");
      out.write("              }\r\n");
      out.write("            else if(\"사원관리\"==node.text){\r\n");
      out.write("         \t\t\t$(\"#r_member\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_rental\").hide();\r\n");
      out.write("        \t\t\t$(\"#r_prod\").hide();\r\n");
      out.write("            \t\t$(\"#r_emp\").show();\r\n");
      out.write("              }\r\n");
      out.write("\t       }\r\n");
      out.write("       });////////////end of tree\r\n");
      out.write("   \r\n");
      out.write("  });///////////////////////end of ready function(돔 구성 완료됐을 때 실행)\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"cc\" class=\"easyui-layout\" style=\"width: 1000px; height: 550px\">\r\n");
      out.write("\t\t<div data-options=\"region:'west',split:true\" title=\"HIFIVE\"\r\n");
      out.write("\t\t\tstyle=\"width: 250px;\">\r\n");
      out.write("\t\t\t<div style=\"margin: 20px 0;\"></div>\r\n");
      out.write("\t\t\t<!--====================로그인 화면 처리 시작================== -->\r\n");
      out.write("\t\t\t<div id=\"r_login\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input id=\"r_id\" name=\"mem_id\">\r\n");
      out.write("\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input id=\"r_pw\" name=\"mem_pw\">\r\n");
      out.write("\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"javascript:loginAction()\" class=\"easyui-linkbutton\">로그인</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:loginAction()\" class=\"easyui-linkbutton\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t <!-- 네이버아이디로로그인 버튼 노출 영역 -->\r\n");
      out.write("\t\t\t\t<!-- <div id=\"naver_id_login\"></div> -->\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t  \t<!--네이버로 로그인 성공했을 때 이동할 페이지================보기 싫어서 죽여놓음===============-->\r\n");
      out.write("\t\t/* \t\t  \tvar naver_id_login = new naver_id_login(\"JGAjK7E5iTq5emPmn6y0\", \"http://localhost:8000/dev_html/ajax/index_ajax.html\");\r\n");
      out.write("\t\t\t\t  \tvar state = naver_id_login.getUniqState();\r\n");
      out.write("\t\t\t\t  \tnaver_id_login.setButton(\"green\", 2,40);\r\n");
      out.write("\t\t\t\t  \tnaver_id_login.setDomain(\"http://localhost:8000/dev_html/easyUI_layout/layout_1.html\");\r\n");
      out.write("\t\t\t\t  \tnaver_id_login.setState(state);\r\n");
      out.write("\t\t\t\t  \tnaver_id_login.setPopup();\r\n");
      out.write("\t\t\t\t  \tnaver_id_login.init_naver_id_login(); */\r\n");
      out.write("\t\t\t \t</script> \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t          $('#r_id').textbox({\r\n");
      out.write("\t\t\t\t    //buttonText:'ID',\r\n");
      out.write("\t\t\t\t    iconCls:'icon-man',\r\n");
      out.write("\t\t\t\t    iconAlign:'right',\r\n");
      out.write("\t\t\t\t    prompt:'아이디'\r\n");
      out.write("\t\t})    \r\n");
      out.write("\t\t\t          $('#r_pw').textbox({\r\n");
      out.write("\t\t\t\t    //buttonText:'Password',\r\n");
      out.write("\t\t\t\t    iconCls:'icon-lock',\r\n");
      out.write("\t\t\t\t    iconAlign:'right',\r\n");
      out.write("\t\t\t\t    prompt:'비밀번호'\r\n");
      out.write("\t\t})\r\n");
      out.write("   </script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--============================== 로그인 화면 처리 끝 ============================== -->\r\n");
      out.write("\t\t\t<!--=========================== 로그아웃 화면 처리 시작 ============================== -->\r\n");
      out.write("\t\t\t<div id=\"r_logout\" align=\"center\">\r\n");
      out.write("\t\t\t\t<span id=\"s_msg\"></span>\r\n");
      out.write("\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:logoutAction()\" class=\"easyui-linkbutton\">로그아웃</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:memberUpdate()\" class=\"easyui-linkbutton\">정보수정</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--=========================== 로그아웃 화면 처리 끝 ================================ -->\r\n");
      out.write("\t\t\t<!--============================== 메뉴 트리 시작 ================================== -->\r\n");
      out.write("\t\t\t<!--  <div style=\"margin:20px 0; margin-left: 15px\"> -->\r\n");
      out.write("\t\t\t<ul id=\"te_menu\" class=\"easyui-tree\">\r\n");
      out.write("\t\t\t\t<li data-options=\"state:'closed'\"><span>회원관리</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><span>회원등록</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>회원수정</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>회원삭제</span></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li data-options=\"state:'closed'\"><span>대여관리</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>대여목록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>대여등록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>대여수정</li>\r\n");
      out.write("\t\t\t\t\t\t<li>대여삭제</li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li data-options=\"state:'closed'\"><span>상품관리</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>상품목록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>상품등록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>상품수정</li>\r\n");
      out.write("\t\t\t\t\t\t<li>상품삭제</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li data-options=\"state:'closed'\"><span>사원관리</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>사원목록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>사원등록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>사원수정</li>\r\n");
      out.write("\t\t\t\t\t\t<li>사원삭제</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!--============================== 메뉴 트리 끝 ============================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center',title:'Rental 관리 시스템'\">\r\n");
      out.write("\t\t\t<!--회원관리-->\r\n");
      out.write("\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t<div id=\"r_member\">Home - 회원관리\r\n");
      out.write("\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("===============================================================================\r\n");
      out.write("\t\t\t\t\t\t\t\t회원 관리 페이지 구현 \r\n");
      out.write("==============================================================================\r\n");
      out.write(" -->\r\n");
      out.write("\t\t\t\t<!--data-options=\"title:'회원목록'\"-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table id=\"dg_member\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"url:'./jsonMember.json',title:'회원목록'\" width=\"700px\"\r\n");
      out.write("\t\t\t\t\theight=\"450px\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--============================== 회원 관리 화면에 필요한 툴바 시작 ============================== -->\r\n");
      out.write("\t\t\t\t<div id=\"rbar_member\">\r\n");
      out.write("\t\t\t\t\t<table align='left' width=\"750px\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 조건 검색 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> &nbsp 이름 :</label> <input class=\"easyui-searchbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your name please!' , searcher:nameSearch\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 140px;\"> <label> &nbsp H.P :</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-maskedbox\" mask=\"999-9999-9999\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 140px\"> <label> &nbsp 생년월일 :</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-datebox\" style=\"width: 140px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"ft\" style=\"padding: 2px 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain=\"true\">조회</a> <a href=\"javascript:addForm()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:updForm()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls=\"icon-edit\" plain=\"true\">수정</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--============================== 회원 관리 화면에 필요한 툴바 끝! ============================== -->\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 등록 화면 시작 ===================================== -->\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\teasyUI에서 제공하는 API활용시 주요속성\r\n");
      out.write("\t\tid를 통해서 자바스크립트로 이벤트 처리하거나 옵션 추가 등 기능처리가 이루어짐\r\n");
      out.write("\t\t해당 콤포넌트에 대한 상세 속성들은 data-options 에 추가하면 됨\r\n");
      out.write("\t\t자바스크립트에서도 속성을 추가하거나 변경할 수 있음. - 방법확인 해 줄 것\r\n");
      out.write("\t\t태그 안에서 속성 추가시 더블 쿼테이션으로 묶어주고 속성과 값은 따로 분리하되\r\n");
      out.write("\t\t기호는 : 콜론을 사용함.\r\n");
      out.write("\t\t태그마다 스타일 속성을 따로 처리할 때는 style 속성에 값 자리에 속성과 값을 주면 됨.\r\n");
      out.write("\t\t제공되는 콤퍼넌트들은 모두 자바스크립트 코드로도 화면 처리 가능함.\r\n");
      out.write("\t\t3가지 방법에 대해서는 별도로 혼자서 반드시 해볼것.\r\n");
      out.write("\t\t외부에 CSS 사용보다는 각 태그 내에 있는 style 속성이 우선하여 적용됨.\r\n");
      out.write("  -->\r\n");
      out.write("\t\t\t\t<div id=\"dlg_add\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"footer:'#rbar_add', closed:true,cache:false, modal:true \"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-dialog\" title=\"회원등록\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 600px; height: 550px; padding: 10px\">\r\n");
      out.write("\t\t\t\t\t<form id=\"f_add\" method=\"get\" action=\"memberAdd.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<table border='1'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your id'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your name'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your address'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your hp'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your gender'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>생일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-datebox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your birthday',formatter:myformatter,parser:myparser\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>코멘트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your comments'\" multiline=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px; height: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"rbar_add\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:add()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\ticonCls=\"icon-ok\" plain=\"true\">저장</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:cancel()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\ticonCls=\"icon-cancel\" plain=\"true\">취소</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 등록 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 수정 화면 시작 ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 수정 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 삭제 화면 시작 ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 삭제 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t===============================================================================\r\n");
      out.write("\t\t\t\t\t\t\t\t사원 관리 페이지 구현 \r\n");
      out.write("\t\t\t\t===============================================================================\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 사원관리 -->\r\n");
      out.write("\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t<div id=\"r_emp\">\r\n");
      out.write("\t\t\t\t사원관리\r\n");
      out.write("\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t===============================================================================\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t사원 관리 페이지 구현 \r\n");
      out.write("\t\t\t\t==============================================================================\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t<!--data-options=\"title:'사원목록'\"-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table id=\"dg_emp\" data-options=\"title:'사원목록'\" width=\"700px\"\r\n");
      out.write("\t\t\t\t\theight=\"450px\" class=\"easyui-datagrid\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<!--============================== 사원 관리 화면에 필요한 툴바 시작 ============================== -->\r\n");
      out.write("\t\t\t\t<div id=\"rbar_emp\">\r\n");
      out.write("\t\t\t\t\t<table align='left' width=\"750px\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 조건 검색 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> &nbsp 이름 :</label> <input class=\"easyui-searchbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your name please!' , searcher:nameSearch\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 140px;\"> <label> &nbsp H.P :</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-maskedbox\" mask=\"999-9999-9999\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 140px\"> <label> &nbsp 생년월일 :</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-datebox\" style=\"width: 140px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 5px 0;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"ft\" style=\"padding: 2px 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain=\"true\">조회</a> <a href=\"javascript:addForm()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:updForm()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls=\"icon-edit\" plain=\"true\">수정</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--============================== 사원 관리 화면에 필요한 툴바 끝! ============================== -->\r\n");
      out.write("\t\t\t\t<!-- ============================= 사원 정보 등록 화면 시작 ===================================== -->\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\teasyUI에서 제공하는 API활용시 주요속성\r\n");
      out.write("\t\tid를 통해서 자바스크립트로 이벤트 처리하거나 옵션 추가 등 기능처리가 이루어짐\r\n");
      out.write("\t\t해당 콤포넌트에 대한 상세 속성들은 data-options 에 추가하면 됨\r\n");
      out.write("\t\t자바스크립트에서도 속성을 추가하거나 변경할 수 있음. - 방법확인 해 줄 것\r\n");
      out.write("\t\t태그 안에서 속성 추가시 더블 쿼테이션으로 묶어주고 속성과 값은 따로 분리하되\r\n");
      out.write("\t\t기호는 : 콜론을 사용함.\r\n");
      out.write("\t\t태그마다 스타일 속성을 따로 처리할 때는 style 속성에 값 자리에 속성과 값을 주면 됨.\r\n");
      out.write("\t\t제공되는 콤퍼넌트들은 모두 자바스크립트 코드로도 화면 처리 가능함.\r\n");
      out.write("\t\t3가지 방법에 대해서는 별도로 혼자서 반드시 해볼것.\r\n");
      out.write("\t\t외부에 CSS 사용보다는 각 태그 내에 있는 style 속성이 우선하여 적용됨.\r\n");
      out.write("  -->\r\n");
      out.write("\t\t\t\t<div id=\"dlg_add\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"footer:'#rbar_add', closed:true, cache:false, modal:true \"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-dialog\" title=\"회원등록\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 600px; height: 550px; padding: 10px\">\r\n");
      out.write("\t\t\t\t\t<form id=\"f_add\" method=\"get\" action=\"memberAdd.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<table border='1'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your id'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your name'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your address'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your hp'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your gender'\" style=\"width: 440px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>생일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-datebox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your birthday',formatter:myformatter,parser:myparser\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>코멘트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'Enter your comments'\" multiline=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 440px; height: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"rbar_add\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:add()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\ticonCls=\"icon-ok\" plain=\"true\">저장</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:cancel()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\ticonCls=\"icon-cancel\" plain=\"true\">취소</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 등록 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 수정 화면 시작 ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 수정 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 삭제 화면 시작 ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ============================= 회원 정보 삭제 화면 끝! ===================================== -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t===============================================================================\r\n");
      out.write("\t\t\t\t\t\t\t\t\t회원 관리 페이지 구현 \r\n");
      out.write("\t===============================================================================\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--대여관리-->\r\n");
      out.write("\t\t\t<div id=\"r_rental\">대여관리</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--상품관리-->\r\n");
      out.write("\t\t\t<div id=\"r_prod\">상품관리</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
