/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-15 10:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/JEasyUICommon.jsp", Long.valueOf(1564466205580L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	List<Map<String, Object>> boardDetail
		=(List<Map<String, Object>>)request.getAttribute("boardDetail");
   	Map<String,Object> rMap = new HashMap<>();
   	  /* 
   	    *마이바티스 사용시 자동으로 담아주므로 VO의 경우
   	    *사용자가 대소문자를 구분해서 사용하지만
   	    *Map의 경우 마이바티스가 컬럼명을 기준으로 자동으로 키값을 생성하는데 
   	    *디폴트가 대문자임.
   	    */
   	if(boardDetail!=null){
   		rMap= boardDetail.get(0);
   	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글 상세보기</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css?1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/commons.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.cookie.js\"></script>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar imsi2;\r\n");
      out.write("\tfunction addAction(){\r\n");
      out.write("\t\t$('#f_boardAdd').attr(\"method\",\"post\");\r\n");
      out.write("\t\t$('#f_boardAdd').attr(\"action\",\"/board/test.nb?crud=boardAdd\");\r\n");
      out.write("\t\t$('#f_boardAdd').submit();\r\n");
      out.write("\t\t//부모창에 함수를 호출할 때 opener.함수명();\r\n");
      out.write("\t\topener.boardList();\r\n");
      out.write("\t\tself.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t//있던 파일 삭제\r\n");
      out.write("\tfunction fileDel(){\r\n");
      out.write("\t\t//원래 있던 파일 이름 받아오기\r\n");
      out.write("\t\timsi2 = $(\"#filebox\").filebox('getText');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//원래 있던 파일 \"\" 이렇게 만들고 받아오기.\r\n");
      out.write("\t\t$(\"#filebox\").filebox('setText',' ');\r\n");
      out.write("\t}\r\n");
      out.write("\t//삭제\r\n");
      out.write("\tfunction deleteForm(){\r\n");
      out.write("\t\t$(\"#dlg_boardDel\").dialog({\r\n");
      out.write("\t\t \t buttons: btn_boardDel \r\n");
      out.write("\t\t\t,title:'글삭제'\r\n");
      out.write("\t\t\t,width: '420px'\r\n");
      out.write("\t\t\t,height: '250px'\r\n");
      out.write("\t\t\t,modal: true\r\n");
      out.write("\t\t\t,href:'boardDelForm.jsp?'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#dlg_boardDel').dialog('open');\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* \t\t$('#f_boardRead').attr(\"method\",\"post\");\r\n");
      out.write("\t\t$('#f_boardRead').attr(\"action\",\"/board/test.nb?crud=boardDel\");\r\n");
      out.write("\t\t$('#f_boardRead').submit();\r\n");
      out.write("\t\t$('#pan_read').panel('close'); */\r\n");
      out.write("\t}\r\n");
      out.write("    function boardDel(){\r\n");
      out.write("    \tvar db_pw = ");
      out.print(rMap.get("BM_PW"));
      out.write(";\r\n");
      out.write("    \t//현재 내가 위치하는 페이지와 비번 입력받는 화면이 다르다. 접근이 가능한가?\r\n");
      out.write("    \tvar u_pw = $(\"#u_pw\").passwordbox('getValue');\r\n");
      out.write("    \t//alert(db_pw + \", \"+u_pw);\r\n");
      out.write("    \t/*\r\n");
      out.write("    \t사용자가 입력한 비번과 DB에서 읽어들인 비번을 비교하여 일치하면 삭제 처리 진행\r\n");
      out.write("    \t불일치시 비번을 다시 입력받도록 한다.\r\n");
      out.write("    \t*/\r\n");
      out.write("    \tif(db_pw == u_pw){ //비번이 일치했을 때 삭제 프로세스를 태운다.\r\n");
      out.write("    \t\t//alert(\"같다\");\r\n");
      out.write("    \t\t$.messager.confirm('Confirm','R U SURE?',function(r){\r\n");
      out.write("    \t\t\tif(r){\r\n");
      out.write("    \t\t\t\tlocation.href=\"/board/test.nb?crud=boardDel&bm_no=");
      out.print(rMap.get("BM_NO"));
      out.write("&bs_file=");
      out.print(rMap.get("BS_FILE"));
      out.write("\"\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t//alert(\"다르다\"); \r\n");
      out.write("    \t\t$(\"#bm_pw\").passwordbox('setValue','');\r\n");
      out.write("    \t}\r\n");
      out.write("    } \r\n");
      out.write("\tfunction boardDelClose(){\r\n");
      out.write("\t\t$('#dlg_boardDel').dialog('close');\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//댓글쓰기\r\n");
      out.write("\tfunction replyForm(){\r\n");
      out.write("\t\t$(\"#dlg_boardAdd\").dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\t//수정\r\n");
      out.write("    function boardUpd(){\r\n");
      out.write("    \tvar db_pw = ");
      out.print(rMap.get("BM_PW"));
      out.write(";\r\n");
      out.write("    \t//현재 내가 위치하는 페이지와 비번 입력받는 화면이 다르다. 접근이 가능한가?\r\n");
      out.write("    \tvar u_pw = $(\"#u_pw\").passwordbox('getValue');\r\n");
      out.write("    \t//alert(db_pw + \", \"+u_pw);\r\n");
      out.write("    \t/*\r\n");
      out.write("    \t사용자가 입력한 비번과 DB에서 읽어들인 비번을 비교하여 일치하면 삭제 처리 진행\r\n");
      out.write("    \t불일치시 비번을 다시 입력받도록 한다.\r\n");
      out.write("    \t*/\r\n");
      out.write("    \tif(db_pw == u_pw){ //비번이 일치했을 때 삭제 프로세스를 태운다.\r\n");
      out.write("    \t\t$(\"#dlg_boardUpd\").dialog('close');\r\n");
      out.write("    \t\tupdateForm();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\talert(\"비밀번호 틀렸어!\"); \r\n");
      out.write("    \t\t$(\"#u_pw\").passwordbox('setText','');\r\n");
      out.write("    \t}\r\n");
      out.write("    } \r\n");
      out.write("\t\r\n");
      out.write("\tfunction updatecheck(){\r\n");
      out.write("\t\t$(\"#dlg_boardUpd\").dialog({\r\n");
      out.write("\t\t \t buttons: btn_boardUpd\r\n");
      out.write("\t\t\t,title:'글수정'\r\n");
      out.write("\t\t\t,width: '420px'\r\n");
      out.write("\t\t\t,height: '250px'\r\n");
      out.write("\t\t\t,modal: true\r\n");
      out.write("\t\t\t,href:'boardUpdForm.jsp?'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#dlg_boardUpd').dialog('open');\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateForm(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#bm_title\").textbox('readonly',false);\r\n");
      out.write("\t\t$(\"#bm_writer\").textbox('readonly',false);\r\n");
      out.write("\t\t$(\"#bm_email\").textbox('readonly',false);\r\n");
      out.write("\t\t$(\"#bm_content\").textbox('readonly',false);\r\n");
      out.write("\t\t$('#upd').hide();\r\n");
      out.write("\t\t$('#tb_file').hide();\r\n");
      out.write("\t\t$('#updsave').show();\r\n");
      out.write("\t\t$('#bs_file_edit').show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction boardUpdClose(){\r\n");
      out.write("\t\t$(\"#dlg_boardUpd\").dialog('close');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction saveForm(){\r\n");
      out.write("\t\t$(\"#bs_filee\").textbox('setValue',imsi2);\r\n");
      out.write("\t\t$(\"#filebox\").filebox('setValue',imsi2);\r\n");
      out.write("\t\t$('#f_boardRead').attr(\"method\",\"post\");\r\n");
      out.write("\t\t$('#f_boardRead').attr(\"action\",\"/board/test.nb?crud=boardUpd\");\r\n");
      out.write("\t\t$('#f_boardRead').submit();\r\n");
      out.write("\t\t$('#pan_read').panel('close');\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//목록\r\n");
      out.write("\tfunction boardList(){\r\n");
      out.write("\t\tlocation.href=\"/board/test.nb?crud=boardList\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function (){\r\n");
      out.write("\t\t$('#updsave').hide();\r\n");
      out.write("\t\t$('#bs_file_edit').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- ===============[[상세조회화면 시작]]==================-->\r\n");
      out.write("\t<form id=\"f_boardRead\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"crud\" value=\"boardUpd\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bm_no\" value=\"");
      out.print(rMap.get("BM_NO") );
      out.write("\">\r\n");
      out.write("\t\t<table id=\"pan_read\" class=\"easyui-panel\" title=\"글상세보기\" data-options=\" modal:'true', footer:'#tb_read'\"\r\n");
      out.write("\t\t\t   style=\"width:550px;height:380px;padding:10px; background:ivory;\">\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">제목</td>  \r\n");
      out.write("\t\t    \t<td width=\"500px\"> \r\n");
      out.write("\t\t    \t<input class=\"easyui-textbox\" value=\"");
      out.print(rMap.get("BM_TITLE") );
      out.write("\" data-options=\"width:'250px', readonly:'true'\" id=\"bm_title\" name=\"bm_title\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t       <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">작성자</td>\r\n");
      out.write("\t\t    \t<td width=\"500px\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-textbox\" value=\"");
      out.print(rMap.get("BM_WRITER") );
      out.write("\" data-options=\"width:'250px', readonly:'true'\" id=\"bm_writer\" name=\"bm_writer\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t       <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">이메일</td>\r\n");
      out.write("\t\t    \t<td width=\"500px\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-textbox\" value=\"");
      out.print(rMap.get("BM_EMAIL") );
      out.write("\" data-options=\"width:'250px', readonly:'true'\" id=\"bm_email\" name=\"bm_email\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t       <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">내용</td>\r\n");
      out.write("\t\t    \t<td width=\"500px\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-textbox\" value=\"");
      out.print(rMap.get("BM_CONTENT") );
      out.write("\" data-options=\"width:'250px',height:'200px',multiline:'true', readonly:'true'\" id=\"bm_content\" name=\"bm_content\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t       <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">비번</td>\r\n");
      out.write("\t\t    \t<td width=\"500px\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-passwordbox\" value=\"");
      out.print(rMap.get("BM_PW") );
      out.write("\" data-options=\"width:'250px'\" id=\"bm_pw\" name=\"bm_pw\" required></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    \t<td width=\"100px\">첨부파일</td>\r\n");
      out.write("\t\t    \t<td width=\"500px\">\r\n");
      out.write("\t\t    \t<span id=\"tb_file\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-textbox\" value=\"");
      out.print(rMap.get("BS_FILE"));
      out.write("\" data-options=\"width:'250px'\" id=\"bs_filee\" name=\"bs_filee\">\r\n");
      out.write("\t\t    \t</span>\r\n");
      out.write("\t\t    \t<span id=\"bs_file_edit\">\r\n");
      out.write("\t\t    \t<input class=\"easyui-filebox\"  value=\"");
      out.print(rMap.get("BS_FILE"));
      out.write("\" data-options=\"width:'250px'\" id=\"filebox\" name=\"bs_file\">\r\n");
      out.write("\t   \t\t\t<a href=\"javascript:fileDel()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">파일삭제</a></td>\r\n");
      out.write("\t   \t\t\t</span>\r\n");
      out.write("\t   \t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- =======================================[[상세조회화면 끝]]===============================-->\r\n");
      out.write("\t\t<!-- 입력 화면 버튼 추가 -->\r\n");
      out.write("\t\t<div id=\"tb_read\" align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"javascript:replyForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\"> 댓글</a>\r\n");
      out.write("\t\t\t<span id=\"upd\">\r\n");
      out.write("\t\t\t<a href=\"javascript:updatecheck()\"  class=\"easyui-linkbutton\" iconCls=\"icon-add\" > 수정</a>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<span id=\"updsave\">\r\n");
      out.write("\t\t\t<a href=\"javascript:saveForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\"> 수정저장</a>\r\n");
      out.write("\t\t<!-- \t<input href=\"javascript:saveForm()\"  class=\"easyui-linkbutton\" iconCls=\"icon-add\"> -->\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<a href=\"javascript:deleteForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\"> 삭제</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:boardList()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" >목록</a>\r\n");
      out.write("\t\t</div>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ===============[[상세조회화면 끝]]==================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 수정하기, 삭제하기, 댓글쓰기, 목록 버튼 -->\r\n");
      out.write("<!-- ===================[[글 수정하기]]====================== -->\r\n");
      out.write("<div id=\"dlg_boardUpd\" class=\"easyui-dialog\" data-options=\"closed:true\" style=\"padding:20px 50px \">\r\n");
      out.write("\t<div id=\"btn_boardUpd\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:boardUpd()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">확인</a>\r\n");
      out.write("\t\t<a href=\"javascript:boardUpdClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">닫기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ===================[[글 수정하기]]====================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- ===================[[글 삭제하기]]====================== -->\r\n");
      out.write("<div id=\"dlg_boardDel\" class=\"easyui-dialog\" data-options=\"closed:true\" style=\"padding:20px 50px \">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 확인 버튼과 닫기 버튼 추가 -->\r\n");
      out.write("\t<div id=\"btn_boardDel\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:boardDel()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">확인</a>\r\n");
      out.write("\t\t<a href=\"javascript:boardDelClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">닫기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ===================[[글 삭제하기]]====================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ====================[[댓글 쓰기]]====================== -->\r\n");
      out.write("<div id=\"dlg_boardAdd\" title=\"댓글쓰기\" class=\"easyui-dialog\" data-options=\"closed:'true', modal:'true', footer:'#tb_boardAdd'\" style=\"width:600px;height:550px;padding:10px;\" >\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t\tform 전송시 enctype 옵션이 추가되면 request객체로 사용자가 입력한 값을 꺼낼 수 없다. \r\n");
      out.write("\t\tMultipartRequest => cos.jar\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t<form id=\"f_boardAdd\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<!--  \t<input type=\"hidden\" name=\"crud\" value=\"boardAdd\"> -->\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bm_no\" value=\"");
      out.print(rMap.get("BM_NO") );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bm_group\" value=\"");
      out.print(rMap.get("BM_GROUP"));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bm_pos\" value=\"");
      out.print(rMap.get("BM_POS"));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bm_step\" value=\"");
      out.print(rMap.get("BM_STEP"));
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <table>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t    \t<td width=\"100px\">제목</td>  \r\n");
      out.write("\t    \t<td width=\"500px\">\r\n");
      out.write("\t    \t<input class=\"easyui-textbox\" data-options=\"width:'250px'\" id=\"bm_title\" name=\"bm_title\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t    \t<td width=\"100px\">작성자</td>\r\n");
      out.write("\t    \t<td width=\"500px\">\r\n");
      out.write("\t    \t<input class=\"easyui-textbox\" data-options=\"width:'250px'\" id=\"bm_writer\" name=\"bm_writer\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t    \t<td width=\"100px\">이메일</td>\r\n");
      out.write("\t    \t<td width=\"500px\">\r\n");
      out.write("\t    \t<input class=\"easyui-textbox\" data-options=\"width:'250px'\" id=\"bm_email\" name=\"bm_email\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t    \t<td width=\"100px\">내용</td>\r\n");
      out.write("\t    \t<td width=\"500px\">\r\n");
      out.write("\t    \t<input class=\"easyui-textbox\" data-options=\"width:'250px',height:'200px'\" id=\"bm_content\" name=\"bm_content\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t    \t<td width=\"100px\">비번</td>\r\n");
      out.write("\t    \t<td width=\"500px\">\r\n");
      out.write("\t    \t<input class=\"easyui-passwordbox\" data-options=\"width:'250px'\" id=\"bm_pw\" name=\"bm_pw\" required></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 입력 화면 버튼 추가 -->\r\n");
      out.write("<div id=\"tb_boardAdd\" align=\"right\">\r\n");
      out.write("\t<a href=\"javascript:addAction()\" class=\"easyui-linkbutton\" iconCls=\"icon-save\"> 저장</a>\r\n");
      out.write("\t<a href=\"javascript:$('#dlg_boardAdd').dialog('close')\" iconCls=\"icon-clear\" class=\"easyui-linkbutton\"> 닫기</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ====================[[댓글 쓰기]]====================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
